[tool.black]
line-length = 88
target-version = ["py310"]
skip-string-normalization = true  # amerikanische Schreibweise, lowercase "true"

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "E203",  # Damit es Black-kompatibel bleibt
    "W503"   # Line break vor dem binären Operator
]
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "venv",
    ".venv"
]

[tool.mypy]
ignore_missing_imports = true
strict_optional = true
